#!/bin/bash
echo "*********************************************************"
echo "Running git pre-commit hook. Running Linting... "
echo "*********************************************************"

# Gather the staged files - to make sure changes are saved only for these files.
stagedFiles=$(git diff --staged --name-only)

# run linting
make lint-detekt; make lint-ktlint

status=$?

if [ "$status" = 0 ] ; then
    echo "Linting found no problems."
    # Add staged file changes to git
    for file in $stagedFiles; do
      if test -f "$file"; then
        git add $file
      fi
    done
    #Exit
    exit 0
else
    echo "*********************************************************"
    echo "       ********************************************      "
    echo 1>&2 "Linting found violations it could not fix."
    echo "Run make format apply in your terminal and fix the issues before trying to commit again."
    echo "       ********************************************      "
    echo "*********************************************************"
    #Exit
    exit 1
fi